server:
  port: 8085

spring:
  application:
    name: rabbitmq-consumer
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    username: 1242202279@qq.com
    password: effagvizxkeqfedc

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

mail:
  from: 1242202279@qq.com
