server:
  port: 8085

spring:
  application:
    name: rabbitmq-consumer
  boot:
    admin:
      client:
        url: http://localhost:8888
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    username: 1242202279@qq.com
    password: effagvizxkeqfedc

mail:
  from: 1242202279@qq.com
