server:
  port: 6066

spring:
  application:
    name: activemq-producer
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    close-timeout: 5000
    send-timeout: 3000
    pool:
      enabled: true
      max-connections: 20

queue:
  name: queue0-test
topic:
  name: topic-test

logging:
  config: classpath:log4j2.xml
  file: logs/${spring.application.name}_info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always