server:
  port: 9094

spring:
  application:
    name: kafka-producer
  kafka:
    # kafka地址，多个地址之间用逗号分隔
    bootstrap-servers: 127.0.0.1:9092
    # 生产者配置
    producer:
      retries: 1
      batch-size: 16384
      # 缓冲等待被发送到服务器的记录的总字节数 32M
      buffer-memory: 33554432
