server:
  port: 7077

spring:
  application:
    name: rocketmq-producer

rocketmq:
  # 是否开启自动配置
  isEnable: true
  # 生产者配置
  producer:
    # nameServer地址
    name-server-addr: 127.0.0.1:9876
    group-name: rocketmq-producer-group
    # 消息最大长度 默认1024*4(4M)
    max-message-size: 4096
    # 发送消息超时时间 默认3000
    send-message-timeout: 3000
    # 发送消息失败重试次数 默认2
    retry-times-when-send-failed: 2