server:
  port: 7077

spring:
  application:
    name: rocketmq-producer
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin

rocketmq:
  # 是否开启自动配置
  isEnable: true
  # 生产者配置
  producer:
    # nameSrv地址
    namesrv-addr: localhost:9876
    group-name: rocketmq-producer-group
    # 消息最大长度 默认1024*4(4M)
    max-message-size: 4096
    # 发送消息超时时间 默认3000
    send-message-timeout: 3000
    # 发送消息失败重试次数 默认2
    retry-times-when-send-failed: 2

logging:
  config: classpath:log4j2.xml
  file: logs/${spring.application.name}_info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always